### ISSUE TITLE
Non-Interactive commands should execute offline

### ISSUE THREAD

**Issue by sculptex** [0chain/zwalletcli#106]
Commands such as `version` should work offline anyway.

`recoverwallet` should have an offline option, it currently includes RegisterToMiners() call. 

Currently they report error Failed to update network details

**Comment by shaktals** [comment]
I have created the PR #94 that allows conditionally running logic (based on the command executed) as a pre-run hook on the cobra lib. I'm just having a little hard time making system-tests work for it.

**Comment by sculptex** [comment]
@shaktals Its a different issue really, it still tries to connect to network even with your changes. That is, I disconnect network and it gives error.

**Comment by shaktals** [comment]
@sculptex Yeah, my PR doesn't solve that specific issue. But it's a basis for the solution, as we'll have to check which command has been executed before trying to connect. That was not possible in the previous setup.

I'll try to fix the system tests asap, so the solution for this will be real easy to implement.

**Comment by sculptex** [comment]
@shaktals okay, cool.

At the moment it seems that Init takes place even before any commands are parsed.

While we could create a solution for offline wallet recovery in a totally separate repo, it seems that since there is potential for other commands (like version) to also be able to work offline we'd keep it in main cli tools (likewise for zboxcli)?

**Comment by shaktals** [comment]
@sculptex yeah, once the pre-run hook is implemented, it's easy to parse out which command has been invoked and conditionally run the network logic.

**Comment by shaktals** [comment]
I have asked for help to solve the system-tests issue with my PR, I'll update you once we get that solved.

**Comment by shaktals** [comment]
Hye @sculptex, PR #94 has been merged. I'll take a look into this feature request tomorrow.

**Comment by sculptex** [comment]
@shaktals cool, thanks.

I created a standalone solution for wallet creation/restoration at :-
https://github.com/sculptex/zcnwalletutil
but integrated solution obviously preferable.
