### ISSUE TITLE
[FEATURE] zwallet ls-sharders lists non magic-block sharders

### ISSUE THREAD

**Issue by bbist** [0chain/zwalletcli#11]
**Observation:**
~/.zcn/config.yaml was configured to use 0dns (block_worker) at `one.devnet-0chain.net/dns`. one network had view-change disabled and it's magic block only included first two of the following sharders. But when we ran `./zwallet ls-sharders` we got following response.
```
- ID:         675502b613ba1c5985636e3e92b9a857855a52155e3316bb40fe9607e14167fb
- Host:       one.devnet-0chain.net
- Port:       31101
- ID:         12e317e5d7a4a0a914ec26074e28f00502c735ddf7ac7d156b34e83e39792a9d
- Host:       one.devnet-0chain.net
- Port:       31102
- ID:         43f4f011698db6f2078e6ceb1cd981ab3bd35d07b7ac6fdf7c77aec1feee09be
- Host:       test4.devnet-0chain.net
- Port:       31101
- ID:         fd02f4436692bd9f679fae809f4f140fd4daaa35769ae9c6db1ab9664f766c22
- Host:       test4.devnet-0chain.net
- Port:       31102 
```
First two are expected as they were part of magic-block. But last two shouldn't be shown in `ls-sharders` command.

**Issue:**
Zwalletcli's ls-sharders command uses gosdk. The gosdk's zcncore.GetSharders() method calls minersc's `/getSharderList` API endpoint from magic-block's sharders. Each MB sharder (first two above), returns the sharder list from local MPT, which may be different from magic block's sharder list.
The above response was expected if test4 was using one network's 0dns for magic_block. If at some point in time, sharders from test4 were registered to one network, the magic block nodes saves newly registered sharders in allShardersList indefinitely. That is what is returned by minersc's `/getSharderList` API.

**Possible solution:**
We could show magic-block's sharder when ls-sharders is run. If the client wants to get all the registered sharders, even if they're not present in magic block, we can provide a --all flag to list them.

**Comment by bbist** [comment]
This issue is addressed by PR https://github.com/0chain/zwalletcli/pull/12.
By default `ls-sharders` command will list MagicBlock's sharders. But it provides a `--all` flag that could be used to list all registered sharders along with MagicBlock's sharders.

**Comment by sculptex** [comment]
This breaks JSON using pretty print. JSON output must always be pure JSON. I can't see why anyone needs pretty print json but please remove it from being default and make it an option instead
