### ISSUE TITLE
Change github hosted runner to self hosted runners.

### ISSUE THREAD

**Issue by service-0chain** [0chain/zwalletcli#144]
@cnlangzi
kindly replace the github runner with self hosted runners -->
https://github.com/0chain/zwalletcli/blob/250431d0cba2a701685e45a1a68761afd65648b9/.github/workflows/build-zwallet.yaml#L13 
Tags that can be used for self hosted runners are as `self-hosted, build`

**Comment by cnlangzi** [comment]
it is fixed on https://github.com/0chain/zwalletcli/commit/bac309daabb55bc94ab23f0b66120cce5edcc976
