### ISSUE TITLE
Add `wallet-create` command to generate new wallet

### ISSUE THREAD

**Issue by peterlimg** [0chain/zwalletcli#150]
We need to have the command to generate new wallets, we don't need to save the wallet to disk to avoid corrupting the existing wallet file by accident, which is a disaster if the user did not backup their wallet seed. So print the wallet info to console and users could copy that info and save to any places they want. 

Anyway, we can have option to enable saving the wallet to disk (~/.znc/) folder, but that would require us to check if the same wallet file name exists before saving, we will also need to generate wallet with random file name base on the creation date, etc. So to keep it simple, we can just ignore this option support atm.

**Comment by bisakhmondal** [comment]
Hey @peterlimg, I am new in this community. I can pick it up as some mild warm up.
