### ISSUE TITLE
Zwallet latest windows release doesnot work out of the box

### ISSUE THREAD

**Issue by hm90121** [0chain/zwalletcli#311]
Downloading the zwallet windows.zip from here https://github.com/0chain/zwalletcli
and extracting it for running gives error where as adding dlls from here 
https://github.com/0chain/zboxcli/files/11840033/windows.dll.s.zip in the extracted directory works

Can any body add dlls to the release zip or make it work out of the box ?

**Comment by boddumanohar** [comment]
Update:

Yes, the official source link is not working. But also, 

when I am trying to build the zbox cli using the instructions present in [here](https://github.com/0chain/zboxcli/wiki/Build-Windows#how-to-build-on-windows), I get this error:


```
gcc_libinit_windows.c: In function ‘_cgo_beginthread’:
gcc_libinit_windows.c:136:27: error: implicit declaration of function ‘_beginthread’; did you mean ‘_cgo_beginthread’? [-Werror=implicit-function-declaration]
  136 |                 thandle = _beginthread(func, 0, arg);
      |                           ^~~~~~~~~~~~
      |                           _cgo_beginthread
cc1: all warnings being treated as errors
make: *** [Makefile:32: zbox] Error 1

Administrator@EC2AMAZ-DFNOCN6 UCRT64 ~/zboxcli

```

**Comment by boddumanohar** [comment]
will be fixed by: https://github.com/0chain/zboxcli/pull/524
