### ISSUE TITLE
zwalletcli - Windows - Not able to Install due to some dependencies.

### ISSUE THREAD

**Issue by akc028** [0chain/zwalletcli#314]
zwalletcli - Windows - Not able to Install due to some dependencies.

https://prnt.sc/uLeUAD_01a_n
![Screenshot_2](https://github.com/0chain/zwalletcli/assets/111416843/cdae9ae0-4078-4f23-82e9-626f777bf7c2)

**Comment by boddumanohar** [comment]
@hm90121 regarding windows binaries, both for zbox and zwallet executables,

Generally, if someone wan't to get quick started, then should download the windows binaries from
https://github.com/0chain/zwalletcli/releases/tag/v1.10.0

and after downloading the binaries,

the user should also download the dll files from the zip file:  https://github.com/0chain/zboxcli/files/11840033/windows.dll.s.zip

the user should extract the dll files into the same directory where zwallet is present
```
libgcc_s_seh-1.dll
libstdc++-6.dll
libwinpthread-1.dll
```

now the zwallet binary can be used.

similary for zboxcli also

**Comment by boddumanohar** [comment]
this will be fixed after this ticket: https://github.com/0chain/zwalletcli/issues/311

In the above ticket, we will be adding those required dll files to zwalletcli zip file.
