### ISSUE TITLE
[FEATURE] Add validation to threshold param on createmswallet to avoid panic 

### ISSUE THREAD

**Issue by stewartie4** [0chain/zwalletcli#49]
on staging, zwallet cli dies with a panic when calling createmswallet with a threshold of 0
![image](https://user-images.githubusercontent.com/18306778/133486134-d4692ece-d958-446b-a2f6-1973011e98ca.png)

zwallet cli dies with a panic when calling createmswallet with a threshold of -1
![image](https://user-images.githubusercontent.com/18306778/133486376-ef331222-92dd-4fc3-8dc1-152f07754d1c.png)

Solution:
Add validation to threshold param to error out before trying to create a slice

**Comment by cnlangzi** [comment]
@shaktals  it should be fixed on gosdk. could you raise an issue/pr on gosdk repo too?

**Comment by shaktals** [comment]
@cnlangzi done
