### ISSUE TITLE
[FEATURE] Return send ZCN txn hash on success

### ISSUE THREAD

**Issue by stewartie4** [0chain/zwalletcli#51]
In 0wallet the user does not get a transaction hash back when they send ZCN - only "success" this makes it difficult for the user to verify the transaction later, or keep the id for their records.

![image](https://user-images.githubusercontent.com/18306778/133792651-6ec44a1c-4c57-4645-9109-6247057f16d7.png)

Acceptance criteria:
Return "Send ZCN success with txn ID: [{{id}}]"

**Comment by sculptex** [comment]
For this to be useful to sysadmins, please include --json option,
i'd recommend something like
{"status":"fail"}
OR
{"status":"success";"txid":"b992ecc6a12dc13e97a27ab03c8d9f1a3a768a89b2d508b1db175f0ba9a9c524"}

please see:- https://github.com/0chain/zwalletcli/blob/sculptex-json-getbalance/cmd/getbalance.go or most zboxcli commands for example of --json implementation
